language: objective-c
osx_image: xcode7
before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
script:
- set -o pipefail
- git submodule update --init --recursive
- xcodebuild -project JWT.xcodeproj -scheme JWT test -sdk macosx | xcpretty -c
- pod lib lint --no-clean
